_wandb:
    value:
        cli_version: 0.18.5
        code_path: code/app.py
        m: []
        python_version: 3.11.1
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 23
                - 24
                - 55
            "4": 3.11.1
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
